services:
  app:
    image: php:8.3-apache
    restart: unless-stopped
    ports:
      - '8082:80'
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bookinggodb
      - DB_USERNAME=bookinggouser
      - DB_PASSWORD=AUafJeHesfS32NzYn9y7
    depends_on:
      - db
    entrypoint: ["/bin/sh", "-c", "apt-get update && apt-get install -y libpng-dev libzip-dev zip unzip && docker-php-ext-install pdo_mysql bcmath gd zip && grep -q 'DocumentRoot /var/www/html/public' /etc/apache2/sites-available/000-default.conf || sed -i 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/000-default.conf && a2enmod rewrite && docker-php-entrypoint apache2-foreground"]            
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - MYSQL_ROOT_PASSWORD=laravel_root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
