/**
 * The print document model, as the server builds it.
 *
 * Mirrors `app/Services/Print/PrintDocumentFactory` + `PrintDocument::toArray()`.
 * The renderer NEVER formats money, never formats a date and never invents a
 * fallback: those strings are finished before they leave PHP, which is what makes
 * the preview, the browser print and the server PDF show identical characters.
 */

export type PrintPaper = 'a4' | 'thermal80' | 'label';

export type PrintArtifact =
  | 'invoice'
  | 'receipt'
  | 'report'
  | 'token'
  | 'label'
  | 'manifest'
  | 'fee-schedule'
  | 'doctor-settlement'
  | 'shift-closing';

export type PrintTone = 'default' | 'success' | 'warn' | 'critical' | 'accent' | 'muted';

export interface PrintMark {
  code: string;
  label: string;
  tone: PrintTone;
}

export interface PrintStatus {
  code: string;
  label: string;
  tone: PrintTone;
}

export interface PrintBranding {
  name: string;
  shortName: string;
  tagline: string;
  branch: string;
  addressLine: string;
  contactLine: string;
  registrations: string[];
  logoUrl: string | null;
  logoDataUri: string | null;
  /** Browser-safe logo: the same asset the PDFs embed, as a public URL. */
  reportHeader: string;
  reportFooter: string;
  currency: string;
}

export interface PrintLabeledValue {
  label: string;
  value: string;
}

export interface PrintParty {
  title: string;
  rows: PrintLabeledValue[];
}

export interface PrintItem {
  index: number;
  description: string;
  sub?: string;
  quantity: string;
  unitPrice?: string;
  discount?: string;
  lineTotal: string;
}

export interface PrintTotal {
  label: string;
  value: string;
  emphasis?: boolean;
  tone?: PrintTone;
  raw?: number;
}

export interface PrintPayment {
  when: string;
  method: string;
  reference: string;
  amount: string;
  isRefund?: boolean;
}

export interface PrintSection {
  label: string;
  body: string;
  emphasis?: boolean;
  tone?: PrintTone;
  group?: string;
}

export interface PrintObservation {
  label: string;
  value: string;
}

export interface PrintCriticalLog {
  notifiedTo: string;
  method: string;
  readBack: string;
  when: string;
}

export interface PrintColumn {
  key: string;
  label: string;
  align?: 'left' | 'right' | 'center';
  width?: string;
}

export interface PrintCode {
  kind: string;
  value: string;
  label: string;
  /** Inline vector SVG — the same geometry every other engine draws. */
  svg: string;
  /** The same symbol as an image source, for engines that need one. */
  dataUri: string;
}

export interface PrintNotice {
  tone: PrintTone;
  text: string;
}

export interface PrintSignature {
  caption: string;
  name: string;
  role: string;
  lines: string[];
  statement: string;
  reference: string;
}

export interface PrintPageFoot {
  left: string;
  center: string;
  right: string;
}

export interface PrintRenderGeometry {
  paper: PrintPaper;
  label: string;
  widthMm: number;
  heightMm: number | null;
  safeWidthMm: number;
  contentWidthMm: number;
  feedMm: number;
  fontScale: number;
  margins: { top: number; right: number; bottom: number; left: number };
}

export interface PrintDocumentModel {
  version: number;
  artifact: PrintArtifact;
  artifactLabel: string;
  documentKey: string;
  title: string;
  kindLabel: string;
  paper: PrintPaper;
  render: PrintRenderGeometry;
  /** The `@page` rule this document must be printed with (per-tenant margins). */
  pageCss: string;
  tokensCss: string;
  /** The document stylesheet, generated by the same blade partial the PDFs use. */
  documentCss: string;
  status: PrintStatus | null;
  marks: PrintMark[];
  branding: PrintBranding;
  generatedAt: string;
  meta: PrintLabeledValue[];
  parties: PrintParty[];
  items: PrintItem[];
  totals: PrintTotal[];
  payments: PrintPayment[];
  sections: PrintSection[];
  observations: PrintObservation[];
  criticalLogs: PrintCriticalLog[];
  criticalLogHeading?: string;
  codes: PrintCode[];
  rows: Array<Record<string, string>>;
  columns: PrintColumn[];
  notices: PrintNotice[];
  footerNotes: string[];
  signature: PrintSignature | null;
  pageFoot: PrintPageFoot;
  tokenNumber?: string;
  roomLabel?: string;
  lineCountEstimate?: number;
  options: {
    showLogo: boolean;
    showBarcode: boolean;
    showSignature: boolean;
    currency: string;
  };
}

// ==================== registry & settings ====================

export interface PrintArtifactMeta {
  artifact: PrintArtifact;
  label: string;
  type: 'document' | 'collection';
  description: string;
  allowedPapers: PrintPaper[];
  defaultPaper: PrintPaper;
  permission: string[];
}

export interface PrintCalibrationEntry {
  label: string;
  safeWidthMm: number;
  feedMm: number;
  fontScale: number;
  updatedAt: string;
}

export interface PrintSettingsModel {
  defaultPapers: Record<string, PrintPaper>;
  a4MarginPreset: string;
  thermalSafeWidthMm: number;
  thermalFeedMm: number;
  thermalFontScale: number;
  showLogo: boolean;
  showBarcode: boolean;
  showSignature: boolean;
  currencyStyle: 'symbol' | 'code' | 'sign';
  dateFormat: string;
  invoiceFooterText: string;
  receiptFooterText: string;
  markReprints: boolean;
  calibration: Record<string, PrintCalibrationEntry>;
}

export interface PrintRegistryPayload {
  artifacts: PrintArtifactMeta[];
  settings: PrintSettingsModel;
  paperProfiles: PrintRenderGeometry[];
  currencyStyles: Array<{ style: string; prefix: string }>;
  dateFormats: string[];
  marginPresets: string[];
}
