@include('print.partials.header')
@include('print.partials.meta')
@include('print.partials.rows')
@include('print.partials.totals')
@include('print.partials.sections')
@include('print.partials.signature')
@include('print.partials.footer')
